[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "eole"
version = "0.2.0"

[tool.flake8]
max-line-length = 120
ignore = ["E203", "E731", "W503"]
# exclude = ["tests/*", "migrations/*"]

[tool.black]
line-length = 120


