import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  apiSidebar: [{type: 'autogenerated', dirName: 'reference'}],
  tutorialSidebar: [
    'index',
    'quickstart',
    {
      type: 'category',
      label: 'Key Concepts',
      link: {
        type: 'generated-index',
        description: '"Some key concepts useful to understand."'
      },
      items: [{type: 'autogenerated', dirName: 'concepts'}]
    },
    // {type: 'category', label: 'Features', items: [{type: 'autogenerated', dirName: 'features'}]},
    {
      type: 'category', 
      label: 'Frequently Asked Questions',
      link: {
        type: 'generated-index',
        description: '"Search these questions before raising issues or ask the community."'
      },
      items: [{type: 'autogenerated', dirName: 'FAQ'}]},
    {
      type: 'category',
      label: 'Recipes',
      link: {
        type: 'generated-index',
        description: 'Various recipes to help you get started.'
      },
      items: [{type: 'autogenerated', dirName: 'recipes'}]},
      'contributing'
  ]


  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
