# base image with torch and apex
# relatively lighter than the full-fledged ngc pytorch images
# ARG TORCH_VERSION=2.3.0
ARG CUDA_VERSION=12.1.0
FROM nvidia/cuda:$CUDA_VERSION-devel-ubuntu22.04

ARG TORCH_VERSION==2.3.0


RUN apt-get update && apt-get install -y \
    libprotobuf-dev \
    libprotobuf-c-dev \
    g++ \
    gcc \
    git \
    locales \
    python3-dev \
    python3-pip
    

RUN pip3 install --upgrade pip
RUN pip3 install packaging

# Install torch
RUN CU=$(echo "${CUDA_VERSION%.*}" | sed 's/\.//g'); pip3 install torch==$TORCH_VERSION --index-url "https://download.pytorch.org/whl/cu$CU"

# Install flash-attention
RUN pip install flash-attn --no-build-isolation
