# base image with torch and apex
# relatively lighter than the full-fledged ngc pytorch images
# ARG TORCH_VERSION=2.3.0
ARG CUDA_VERSION=12.1.0
FROM nvidia/cuda:$CUDA_VERSION-devel-ubuntu22.04

ARG TORCH_VERSION==2.3.0


RUN apt-get update && apt-get install -y \
    libprotobuf-dev \
    libprotobuf-c-dev \
    g++ \
    gcc \
    git \
    locales \
    python3-dev \
    python3-pip
    

RUN pip3 install --upgrade pip
RUN pip3 install packaging

# Install torch
RUN CU=$(echo "${CUDA_VERSION%.*}" | sed 's/\.//g'); pip3 install torch==$TORCH_VERSION --index-url "https://download.pytorch.org/whl/cu$CU"

# Install apex
RUN mkdir /setup
WORKDIR /setup
RUN git clone https://github.com/nvidia/apex
WORKDIR /setup/apex
RUN pip3 install ninja
ENV TORCH_CUDA_ARCH_LIST="6.0;6.1;6.2;7.0;7.5;8.6;8.7;9.0+PTX"
RUN export MAX_JOBS=$(nproc); pip3 install -v --no-build-isolation \
    --config-settings --global-option="--cpp_ext" \
    --config-settings --global-option="--cuda_ext" \
    --config-settings --global-option="--deprecated_fused_adam" \
    --global-option="--xentropy" \
    --global-option="--fast_multihead_attn" \
    ./

# Install flash-attention
RUN pip install flash-attn --no-build-isolation
