## Whisper inference — basic English transcription
## Usage:
##   echo "/path/to/audio.wav" > ./audio_files.txt
##   eole predict -config recipes/whisper/whisper_predict.yaml

model_path: "$EOLE_MODEL_DIR/whisper-base-en-eole"
data_type: audio
src: ./audio_files.txt
output: ./transcription.txt
beam_size: 5
max_length: 448
gpu_ranks: [0]
batch_type: sents
batch_size: 1
